---
#first deploing websrv, zabbixsrv, elasticsrv 
- name: Deploing web srv
  hosts: websrv
  remote_user: ubuntu-user
  become: yes
  gather_facts: false
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: "Europe/Moscow"

    - name: Install nginx
      apt: 
        name:
          - nginx
        state: present
        
    - name: Copy site file
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Copy zabbix agent access config
      ansible.builtin.copy:
        src: ./zabbix_agent.conf
        dest: /etc/nginx/conf.d/zabbix_agent.conf

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes    

    - name: Install zabbix repo from the internet
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
    
    - name: refresh cache
      apt:
        update_cache: yes

    - name: install zabbix-agent
      apt:
        name:
          - zabbix-agent
        state: present

    - name: Edit zabbix_agent.conf
      shell: |
         sed -i 's/Server=127.0.0.1/Server=zabbix.ru-central1.internal/g' /etc/zabbix/zabbix_agentd.conf
 
    - name: Restart zabix service
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes

 
- name: Deploing zabbix srv
  hosts: zabbix
  remote_user: ubuntu-user
  become: yes
  gather_facts: false
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: "Europe/Moscow"

    - name: Install zabbix repo from the internet
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
    
    - name: refresh cache
      apt:
        update_cache: yes

    - name: install all for Zabbix
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - apache2
          - zabbix-server-pgsql 
          - zabbix-frontend-php 
          - php8.1-pgsql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - zabbix-agent
        state: present

    - name: create db
      shell: |
        su - postgres -c 'psql --command "CREATE USER zabbix WITH PASSWORD '\'123456789\'';"'
        su - postgres -c 'psql --command "CREATE DATABASE zabbix OWNER zabbix;"'
        zcat zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
    
    - name: pass zabbix_server.conf
      shell: |
        sed -i 's/# DBPassword=/DBPassword=123456789/g' /etc/zabbix/zabbix_server.conf

    - name: Restart zabsrv service
      service:
        name: zabbix-server
        state: restarted
        enabled: yes

    - name: Restart apache service
      service:
        name: apache2
        state: restarted
        enabled: yes

- name: deploing Elastic srv
  hosts: elastic
  remote_user: ubuntu-user
  become: yes
  gather_facts: false
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
         name: "Europe/Moscow"

    - name: install elasticsearch from internet
      apt:
       deb: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.15.0-amd64.deb

    - name: Copy elasticsearch conf #true
      ansible.builtin.copy:
      src: "./elasticsearch.yml"
      dest: /etc/elasticsearch/elasticsearch.yml
      mode: '0644'

    - name: restart elasticsearch
      service:
        name: elasticsearch
      state: restarted
      enabled: yes

